Algoritmo "Estrutura-Para-Faca"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/06/2026
Var
// Seção de Declarações das variáveis 
   numero,fatorial,contador: inteiro
   

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite o seu numero para calcular o fatorial.")
   leia(numero)
   fatorial := 1

   para contador de 1 ate numero faca
      fatorial := fatorial * contador
   fimpara
   escreva("O fatorial de ", numero, " é: " , fatorial)
Fimalgoritmo