Algoritmo "Treinando Tabelas"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/06/2026
Var
// Seção de Declarações das variáveis 
  notas01,notas02=: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo