Algoritmo "Variáveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cleison Melo
// Descrição   : Aprendendo sobre variaveis
// Autor(a)    : Douglas
// Data atual  : 11/06/2026
Var
// Seção de Declarações das variáveis
//primeiro nome
//segundo nome
//idade
//cidade
//endereço

          primeiroNome, segundoNOme, cidade, endereco: caractere
          idade: inteiro




Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo